#!/bin/bash
set -e

# Create user if it doesn't exist
if ! id -u restic_exporter >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /sbin/nologin restic_exporter
fi

# Reload systemd and enable the service
systemctl daemon-reload
systemctl enable restic_exporter.service
systemctl start restic_exporter.service
