name: Build and Publish .rpm

on:
  push:
    tags: # Trigger on new tags (e.g., v1.0.0)
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip ruby ruby-dev rpm
        sudo gem install --no-document fpm

    - name: Build .rpm package
      run: |
        VERSION="${{ github.ref_name }}"
        VERSION="${VERSION#v}"
        pip3 install prometheus_client
        fpm -s dir -t rpm -n restic-prometheus-exporter \
            --version "${VERSION}" --iteration 1 \
            --description "Prometheus exporter for restic backup metrics" \
            --rpm-os linux \
            --rpm-dist el9 \
            --depends python3 \
            --depends python3-pip \
            --depends restic \
            --depends python3-prometheus_client \
            --after-install debian/postinst \
            --after-remove debian/postrm \
            --config-files /opt/restic_exporter/config.ini \
            restic_prometheus_exporter.py=/opt/restic_exporter/restic_prometheus_exporter.py \
            restic_exporter.service=/usr/lib/systemd/system/restic_exporter.service \
            "config example.ini"=/opt/restic_exporter/config.ini

    - name: Generate .repo file
      run: |
        REPO_URL="https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}"
        echo "[restic-prometheus-exporter]" > restic-prometheus-exporter.repo
        echo "name=restic-prometheus-exporter" >> restic-prometheus-exporter.repo
        echo "baseurl=${REPO_URL}" >> restic-prometheus-exporter.repo
        echo "enabled=1" >> restic-prometheus-exporter.repo
        echo "gpgcheck=0" >> restic-prometheus-exporter.repo

    - name: Create Release and Upload .rpm and .repo
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.rpm
          *.repo
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Automated release of restic-prometheus-exporter version ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
